name: CI

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build action
        run: npm run build

      - name: Validate action.yml
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const yaml = require('js-yaml');

            try {
              const action = yaml.load(fs.readFileSync('action.yml', 'utf8'));
              console.log('✅ action.yml is valid YAML');

              // Basic validation
              if (!action.name) throw new Error('Missing action name');
              if (!action.runs) throw new Error('Missing runs configuration');
              if (!action.runs.main) throw new Error('Missing main script');

              console.log('✅ action.yml structure is valid');
            } catch (error) {
              console.error('❌ action.yml validation failed:', error.message);
              process.exit(1);
            }
